spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  servlet:
    session:
      timeout: 10s
